---
   - name: Download Zip and Unzip.
     yum:
       name: [zip, unzip]
       state: present
       
   - name: Download the Nexus file.
     get_url:
         url: "{{nexus_url}}"
         dest: "{{Download_folder}}"

   - name: Changing Permission of nexus file.
     command: chmod 777 /opt/nexus-2.14.16-01-bundle.zip

   - name: Unzipping it.
     unarchive:
       src: /opt/nexus-2.14.16-01-bundle.zip
       dest: /opt
       remote_src: yes 
       
   - name: Now running nexus.
     shell: RUN_AS_USER=root /opt/nexus-2.14.16-01/bin/nexus start
     register: result

   - debug:
        var: result
        verbosity: 2
